name: fastenv
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - xarray
  - cfgrib
  - eccodes
  - httpx
  - matplotlib
  - pip
  - pip:
      - python-multipart
